# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 697)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_browse = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_browse.setFont(font)
        self.btn_browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout_8.addWidget(self.btn_browse)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(434, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(143, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_import = QtWidgets.QPushButton(self.widget)
        self.btn_import.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_import.setStyleSheet("")
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_2.addWidget(self.btn_import, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(228, 35))
        self.comboBox.setMaximumSize(QtCore.QSize(228, 16777215))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setMinimumSize(QtCore.QSize(500, 0))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    border:2px solid white;\n"
"    text-align: center;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"QProgressBar::chunk{\n"
"background-color: rgba(0, 172, 149, 255);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_web_filter = QtWidgets.QPushButton(self.widget)
        self.btn_web_filter.setEnabled(False)
        self.btn_web_filter.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_web_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_web_filter.setStyleSheet("")
        self.btn_web_filter.setObjectName("btn_web_filter")
        self.horizontalLayout_5.addWidget(self.btn_web_filter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 804, 177))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.display = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.display.setText("")
        self.display.setObjectName("display")
        self.gridLayout_3.addWidget(self.display, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Resetbtn = QtWidgets.QPushButton(self.widget)
        self.Resetbtn.setEnabled(False)
        self.Resetbtn.setMinimumSize(QtCore.QSize(0, 30))
        self.Resetbtn.setSizeIncrement(QtCore.QSize(0, 30))
        self.Resetbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Resetbtn.setStyleSheet("")
        self.Resetbtn.setObjectName("Resetbtn")
        self.verticalLayout_3.addWidget(self.Resetbtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(180, 30))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setWordWrap(True)
        self.label_3.setIndent(5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pack_num = QtWidgets.QLabel(self.widget)
        self.pack_num.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pack_num.setFont(font)
        self.pack_num.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pack_num.setText("")
        self.pack_num.setAlignment(QtCore.Qt.AlignCenter)
        self.pack_num.setObjectName("pack_num")
        self.horizontalLayout_2.addWidget(self.pack_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(180, 30))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.web_num = QtWidgets.QLabel(self.widget)
        self.web_num.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.web_num.setFont(font)
        self.web_num.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.web_num.setText("")
        self.web_num.setAlignment(QtCore.Qt.AlignCenter)
        self.web_num.setObjectName("web_num")
        self.horizontalLayout_3.addWidget(self.web_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(180, 30))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.label_7.setWordWrap(True)
        self.label_7.setIndent(5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.ip_num = QtWidgets.QLabel(self.widget)
        self.ip_num.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ip_num.setFont(font)
        self.ip_num.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ip_num.setText("")
        self.ip_num.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_num.setObjectName("ip_num")
        self.horizontalLayout_4.addWidget(self.ip_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setMinimumSize(QtCore.QSize(0, 250))
        self.webEngineView.setMaximumSize(QtCore.QSize(16777215, 391))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout_4.addWidget(self.webEngineView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_browse.setText(_translate("MainWindow", "Browse (Open Capture)"))
        self.pushButton.setText(_translate("MainWindow", "Browse (Save Map)"))
        self.btn_import.setText(_translate("MainWindow", "Run"))
        self.btn_web_filter.setText(_translate("MainWindow", "Open Map"))
        self.Resetbtn.setText(_translate("MainWindow", "Reset"))
        self.label_3.setText(_translate("MainWindow", "Number of captured Packets"))
        self.label_5.setText(_translate("MainWindow", "Number of visited websites"))
        self.label_7.setText(_translate("MainWindow", "Number of distinct IP"))

from PyQt5 import QtWebEngineWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

